   # This workflow builds and tests the project.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# When we add support for a new Emoji version, the test step
# must be disabled until the runner environment adds support
# for all emoji versions.

name: Build Runner

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
env:
  SCHEME: EmojiKit

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
      - name: Build all platforms
        run: bash scripts/build.sh $SCHEME
      - name: Test iOS
        run: bash scripts/test.sh $SCHEME
